title: Comms Black Mobile
description: Official site
url: "https://commsblack.online"
baseurl: ""  # empty because you're using a project pages URL or custom domain via CNAME
markdown: kramdown
kramdown:
  input: GFM
# Collections scaffold (for future pages if you want pretty folders/MD)
collections:
  pages:
    output: true
    permalink: /:path/

# rebuild: 2025-11-08T15:51:23

# rebuild: 2025-11-08T15:59:03

# rebuild: 2025-11-08T16:04:42

# rebuild: 2025-11-08T16:17:16

# rebuild: 2025-11-08T16:27:14

# rebuild: 2025-11-08T16:32:08

# rebuild: 2025-11-08T20:22:32
